feat: persisted, reused term and emacs floating windows
- `mod+d` for opening a dotfile or todo file in emacs
- `mod+r` for running a command in alacritty+tmux

Both persisting and reusing the window if it's in the scratchpad.
Multi-monitor behaviour is untested.

diff --git a/i3/.local/bin/smart-move-focus b/i3/.local/bin/smart-move-focus
--- a/i3/.local/bin/smart-move-focus
+++ b/i3/.local/bin/smart-move-focus
@@ -1,7 +1,9 @@
 #!/bin/bash
 
-# taken from: https://gist.github.com/mijoharas/b9d09daed9654ca8d0d081015209ecd0
-# requires: jq
+########
+# For universal focus-movement, across splits/apps/tabs/everything
+# # TODO: shift+move to move to 'edge', then next app
+########
 
 function get-focused-window()
 {
@@ -104,19 +106,17 @@ function am-i-floating()
 
 function perform-move()
 {
-    res=$(am-i-floating)
-    if [ "$res" = 'user_on' ]; then
-        echo "we got a floater!" >> ~/tmp/errors
-        # TODO close scratchpad window!
-        i3-msg focus mode_toggle
-    else
-        echo "Not floating" >> ~/tmp/errors
-        focused_window=$(get-focused-window)
-        echo "$focused_window is focused" >> ~/tmp/errors
-        if [ "$focused_window" = "Emacs" ]; then
-            emacs-move "$1"
-            result=$?
-            if [ $result -ne 0 ]; then
+    focused_window=$(get-focused-window)
+    echo "$focused_window is focused" >> ~/tmp/errors
+    if [ "$focused_window" = "Emacs" ]; then
+        emacs-move "$1"
+        result=$?
+        if [ $result -ne 0 ]; then
+            res=$(am-i-floating)
+            if [ "$res" = 'user_on' ]; then
+                # TODO close scratchpad window?
+                i3-msg focus mode_toggle
+            else
                 i3-move "$1"
             fi
         elif [ "$focused_window" = "Alacritty" ]; then
@@ -124,10 +124,16 @@ function perform-move()
             tmux-or-vim-move "$1"
             result=$?
             if [ $result -ne 0 ]; then
+                res=$(am-i-floating)
+                if [ "$res" = 'user_on' ]; then
+                    # TODO close scratchpad window?
+                    i3-msg focus mode_toggle
+                else
+                    i3-move "$1"
+                fi
+            else
                 i3-move "$1"
             fi
-        else
-            i3-move "$1"
         fi
     fi
 }
